########################
# REMOTE NAO CONTROL
# April 2012 - Hessel van der Molen
# (c) Dutch Nao Team, licensed under GNU-GPL v3.0 
#
# HOW TO USE:
# 1) Make sure you have installed:
#   - Python 2.7
#   - Naoqi SDK 12.3    (for python 2.7)
#   - Pygame            (for Python 2.7)
# 2) Determine the type of input device you want to use (keyboard, joystick..)
# 3) Check if <inputdevice>.py exists in the 'lib' directory
#           (if not, you have to create it yourself)
# 4) Determine the input-processor & motion-files
#           (you can made these yourself, or use the defaults in 'defaults')
# 5) Connect Nao & Computer to same network
# 6) get Nao-ipadress
# 7) In terminal, goto the dir containing the above described files 
# 8) run: 
#      terminal> python main.py <InputDevice> <EventProcessFile> <NaoIPadress> [optional: <inputID>]
# 7) enjoy :)
#
import sys
import platform
import os

##########################
##      CLASSES
#############

class termOutput:
    cmdDict = {}
    cmdIdx = 0
    cmdSize = 10
    process = None
    
    def __init__(self, cmdSize, process):
        self.cmdSize = cmdSize
        self.process = process
        self.clear()
        
    #display a message that the cmd is executing...
    def execute(self, cmd):
        self.cmdDict[self.cmdIdx] = cmd
        if len(self.cmdDict) > self.cmdSize:
            del self.cmdDict[self.cmdIdx - self.cmdSize]
        self.refresh()
    
    #display a message that the cmd is executed
    def done(self):
        self.refreshLine()
        #increase cmd-index
        self.cmdIdx += 1

    #display the last 'cmdSize' commands from command-list
    # --> if 'cmdSize' = -1, all commands are shown
    def refresh(self):
        if (((self.cmdSize == -1) and (self.cmdIdx == 0)) or (self.cmdSize != -1)):
            self.clear()
            
            sys.stdout.write('\n')
            sys.stdout.write("   --------- REMOTE NAO CONTROL --------- " + '\n')
            sys.stdout.write("           http://dutchnaoteam.nl         " + '\n')
            sys.stdout.write("   -------------------------------------- " + '\n')
            sys.stdout.write('\n')
            sys.stdout.write("  Button Usage for '[" + sys.argv[1] + ", " + sys.argv[2]+  "]': \n")
            sys.stdout.write("  Press '" + process.getQuitCommand() + "' to quit." '\n')
            sys.stdout.write('\n')
            sys.stdout.write( process.getButtonDefinition() )
            sys.stdout.write('\n')
            sys.stdout.write("   -------------------------------------- " + '\n')
            
        if (self.cmdSize != -1):    
            #for i in self.cmdDict:
            for i in xrange(self.cmdIdx-self.cmdSize, self.cmdIdx):
                sys.stdout.write(self.formatLine( i + 1 ))
                if (i != self.cmdIdx):
                    sys.stdout.write(" Done" + '\n')
        else:
            sys.stdout.write(self.formatLine(self.cmdIdx))
        
    def refreshLine(self):
        sys.stdout.write('\r' + self.formatLine(self.cmdIdx) + " Done" + '\n')
        self.waiting()
    
    def waiting(self):
        sys.stdout.write("  Ready for input...")
        
    def formatLine(self,idx):
        line = "  [" + str(idx) + "]" + '\t'
        line += "Sending command: '"
        line += self.cmdDict[idx]
        line += "' ..."
        return line
    
    #clear display
    def clear(self):
        if platform.system() == 'Windows':
            os.system('cls')
        else:
            os.system('clear')

##########################
##      FUNCTIONS
#############
            
def listFiles(dir):
    sys.path.append(dir)
    subdirlist = []
    for item in os.listdir(dir):
        founditem = os.path.join(dir,item)
        if not os.path.isfile(founditem):
            subdirlist.append(founditem)
        for subdir in subdirlist:
            listFiles(subdir) 
            
##########################
##      SYSTEM CALL
#############
                        
if (len(sys.argv) <= 3):
    sys.stdout.write( '\n')
    sys.stdout.write( "Usage:" + '\n\n')
    sys.stdout.write( "bash> python main.py <InputDevice> <EventProcessFile> <MotionFile> <NaoIPadress> [optional: <inputID>]" + '\n')    
    sys.stdout.write( " <InputDevice>     : type of input to read, e.g. 'keyboard' or 'joystick'" + '\n')
    sys.stdout.write( " <EventProcessFile>: file name of file which process the input generated by <InputDevice>, e.g. 'keyDefault'" + '\n')
    sys.stdout.write( " <NaoIPadress>     : ip adress of Nao, e.g. 192.168.0.24" + '\n')
    sys.stdout.write( " <inputID>         : optional, ID of input-object to use when multiple are connected" + '\n')
    sys.stdout.write( '\n')
else: 
    sys.stdout.write( "> Searching folders in current directory... " )
    listFiles(os.getcwd())
    sys.stdout.write( "\r> Searching folders in current directory... done" + '\n')   
    
    sys.stdout.write( "> Importing naoqi... " )
    from naoqi import ALProxy
    sys.stdout.write( "\r> Importing naoqi... done" + '\n')

    motionProxy = None
    poseProxy = None
    IPADRESS = sys.argv[3]
    PORT = 9559
    
    sys.stdout.write( "> Setting connection data... " + '\n' )
    try:
        sys.stdout.write( ">>> setting motion proxy... " + '\n' )
        motionProxy = ALProxy("ALMotion", IPADRESS, PORT)
        sys.stdout.write( "\r>>> setting motion proxy... done" + '\n' )
        sys.stdout.write( ">>> setting pose proxy... " )
        poseProxy = ALProxy("ALRobotPose", IPADRESS, PORT)
        sys.stdout.write( "\r>>> setting pose proxy... done" + '\n')    
    except Exception, ee:
        sys.stdout.write( '\n>> ' + str(ee) + '\n\n')
        sys.stdout.write( "Error: Cannot connect to Nao" + '\n')
        exit()
    sys.stdout.write( "\r> Setting connection data... done" + '\n' )
    
    
    sys.stdout.write( "> Importing event-process file...")
    try:
        process = __import__(sys.argv[2])
        if (not hasattr(process, "init")):
            sys.stdout.write("\nError: Event-Process File '" + sys.argv[2] + "' does not contain the function: 'init'" + '\n')
            exit()
        elif (not hasattr(process, "getButtonDefinition")):
            sys.stdout.write("\nError: Event-Process File '" + sys.argv[2] + "' does not contain the function: 'getButtonDefinition'" + '\n')
            exit()
        elif (not hasattr(process, "processEvent")):
            sys.stdout.write("\nError: Event-Process File '" + sys.argv[2] + "' does not contain the function: 'processEvent'" + '\n')
            exit()
        process.init(motionProxy, poseProxy)
    except Exception, ee:
        sys.stdout.write( '\n>> ' + str(ee) + '\n\n')
        sys.stdout.write( "Error: can't load event-process file: '" + sys.argv[1] + "'" + '\n')
        exit()
    sys.stdout.write( "\r> Importing event-process file... done" + '\n')
    
    
    sys.stdout.write( "> Initializing input-system... " )
    try:
        input = __import__(sys.argv[1])
        if (not hasattr(input, "init")):
            sys.stdout.write("\nError: input-system '" + sys.argv[1] + "' does contain the function: 'init'" + '\n')
            exit()
        elif (not hasattr(input, "getQuitCommand")):
            sys.stdout.write("\nError: input-system  '" + sys.argv[1] + "' does contain the function: 'getQuitCommand'" + '\n')
            exit()
        elif (not hasattr(input, "getAction")):
            sys.stdout.write("\nError: input-system  '" + sys.argv[1] + "' does contain the function: 'getAction'" + '\n')
            exit()      
        input.init(sys.argv)
    except Exception, ee:
        sys.stdout.write( '\n>> ' + str(ee) + '\n\n')
        sys.stdout.write( "Error: can't load input system: '" + sys.argv[1] + "'" + '\n')
        exit()
    sys.stdout.write( "\r> Initializing input-system... done" + '\n')

    #setup display (output)
    output = termOutput(15, process)
    output.refresh()
    output.waiting()

    #start reading input
    while True:
        action = input.getAction()
        if (action == "quit"): 
            sys.stdout.write( "Quitting system" + '\n')
            exit()
        elif ( not(action == None)):
            process.processEvent(output, action)
        