########################################################
# DUMMY EVENTHANDLER FOR REMOTE-NAO-CONTROL FRAMEWORK
########################################################
#   May 2012, Hessel van der Molen, hmolen.science@gmail.com
#   Dutch Nao Team - http://dutchnaoteam.nl
#
#   Requires:
#   - python    [time]
#   
#   This eventHandler can be used for development. 
#   It prints event-result (generated by library of choice) into the terminal

import time

def init(IPADRESS):
    pass
    
def getButtonDefinition():
    text  = "   Dummy\n"
    text  += "   Press any key...\n"
    return text

def processEvent(display, event):
    #display.execute(str(event))
    #display.done()
    #time.sleep(1)
    print str(event)
    time.sleep(0.1)
    